-- case : 전화번호 없는 경우 처리
SELECT PT_NAME, PT_NO, GEND_CD, AGE,
    CASE
        WHEN TLNO IS NULL THEN 'NONE'
        ELSE TLNO
    END AS TLNO
FROM PATIENT
WHERE AGE<=12 and GEND_CD = 'W'
ORDER BY AGE DESC, PT_NAME ASC;
