-- 조건 : 2021, 인문
-- 출력 : 도서id, 출판일
-- 정렬 : 출판일
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE,'%Y-%m-%d') as PUBLISHED_DATE
FROM BOOK
WHERE CATEGORY='인문' and YEAR(PUBLISHED_DATE)=2021
ORDER BY PUBLISHED_DATE ASC;