-- 게시글 아이디를 기준으로 join
-- 조건 : 2022-10 게시글
-- 정렬 : 댓글 작성일 오름차순, 게시글 제목 오름차순
SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS B
    INNER JOIN USED_GOODS_REPLY AS R
    ON B.BOARD_ID = R.BOARD_ID
WHERE YEAR(B.CREATED_DATE)=2022 AND MONTH(B.CREATED_DATE)=10
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;